test: Update to license-test-files bee89662 (Apache-1.0: Add missing closing quote)
Similar to 36bce3f5 (test: Add license-test-files with read-tree,
2018-01-03):

  $ git config remote.test.url https://github.com/wking/license-test-files
  $ git fetch test
  $ git rm -r test
  $ git read-tree --prefix=test/ -u test/apache-1.0-missing-quote
  $ rm test/README.md test/testfiles-1.0-for-license-list-2.6.tar
  $ git add test

The remote.test.url update is because Gary hasn't landed my just-filed
[1].

The 'git rm' call avoids:

  $ git read-tree --prefix=test/ -u test/apache-1.0-missing-quote
  error: Entry 'test/simpleTestForGenerator/0BSD.txt' overlaps with 'test/simpleTestForGenerator/0BSD.txt'.  Cannot bind.

This catches the test data up with 558562e6 (Add missing close quote
to Apache-1.0.xml, 2017-12-30, #588) and b975b3e0 (Remove section
4.g. from BitTorrent-1.0 license, 2017-12-30, #589).

[1]: https://github.com/goneall/license-test-files/pull/2